POST localhost:8090/api/user-problem/solve-user-problem
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBjb2RpbmdiYXQuY29tIiwiaWF0IjoxNjYzOTI4MTQyLCJleHAiOjE2NjQwMDAxNDJ9.NzQbD-AQm3Fw-X-JnyJuiCY74U2YM8PP0fKwaM9FVIonjvdyWrUrsyroCZhdNiqZSfJn5u1JxPBga0h41P7YzA

{

  "problemId": 1,
  "userId": "da23188a-01bd-412e-8156-88b25f7c04ad",
  "solution": "public String smth(String s1, String s2){return a+b;}"

}

###
GET localhost:8090/user-problem/api/list
Content-Type: application/json


###
GET localhost:8090/user-problem/api/get-user-problem?userId=1&problemId=2
Content-Type: application/json


