POST localhost:8090/api/user-problem/solve-user-problem
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBjb2RpbmdiYXQuY29tIiwiaWF0IjoxNjYzOTI5NzM4LCJleHAiOjE2NjQwMDE3Mzh9.DV2Idgawm8Br7IqWVREPKwxpjEDe8SQFU9O1fLH9odqbwwZ3hw246aH4iFoRY9xv3MqB6gtnBjhbVrKcXTvw_g

{
  "problemId": 1,
  "solution": "public String concat(String a, String b){return a+b;}"
}

###
GET localhost:8090/api/user-problem/list
Content-Type: application/json


###
GET localhost:8090/api/user-problem/get-user-problem?userId=1&problemId=2
Content-Type: application/json


