
### Problem qo`shish
POST http://localhost:8090/api/problem
Content-Type: application/json




{
  "title": "problem1",
  "description": "middle range",
  "methodSignature": "asfdad(ASFDAS){}",
  "section": 1,
  "cases": [
    {
      "args": "a, b, d, c",
      "expected": "askdksad",
      "visible": true
    },
    {
      "args": "tfsfkj dscs cdsc",
      "expected": " idc c  icd   sad",
      "visible": false
    },
    {
      "args": "JAHKANJ JDA",
      "expected": "DKSJAKHKCNSKN<W",
      "visible": true
    },
    {
      "args": "!#@!#(*!@)#",
      "expected": "hjdsjkcw  4i ci",
      "visible": true
    },
    {
      "args": "1229739  139229 131",
      "expected": "=-==0=-=0-",
      "visible": false
    }
  ]
}








### Update
PUT http://localhost:8090/api/problem/30
Content-Type: application/json

{
  "title": "Problem",
  "description": "Hard range",
  "methodSignature": "nkdakcasfdad(ASFDAS){}",
  "section": 1,
  "cases": [
    {
      "args": "a, b, d, c",
      "expected": "askdksad",
      "visible": true
    },
    {
      "args": "JAHKANJ JDA",
      "expected": "DKSJAKHKCNSKN<W",
      "visible": true
    },
    {
      "args": "!#@!#(*!@)#",
      "expected": "hjdsjkcw  4i ci",
      "visible": true
    },
    {
      "args": "1229739  139229 131",
      "expected": "=-==0=-=0-",
      "visible": false
    }
  ]
}

