#add user
POST http://185.74.5.104:8165/api/auth/sign-up
Content-Type: application/json

{
  "email": "firdavsolimjonov25@gmail.com",
  "password": "cyberhack25"
}

###

GET http://localhost:80/api/auth/verification-email?email=firdavsolimjonov25@gmail.com
#Content-Type: application/json

