
###  Tizimga kirish
POST localhost:8090/api/auth/sign-in
Content-Type: application/json

{
  "email": "admin@codingbat.com",
  "password": "root123"
}

###  Language qo`shish
POST localhost:8090/api/language/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBjb2RpbmdiYXQuY29tIiwiaWF0IjoxNjYzNjU2NDAzLCJleHAiOjE2NjM3Mjg0MDN9.FvLDuYL62UEa1elWcwt8RX8E5fGpL4SAMtvuAT_Hu94UyIwk3_UKcfPTacRs7FmOK5oDWpANsflnnx_LfbAaLQ

{
  "title": "Java"
}

###  Section qo`shish
POST localhost:8090/api/section/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBjb2RpbmdiYXQuY29tIiwiaWF0IjoxNjYzNjU2NDAzLCJleHAiOjE2NjM3Mjg0MDN9.FvLDuYL62UEa1elWcwt8RX8E5fGpL4SAMtvuAT_Hu94UyIwk3_UKcfPTacRs7FmOK5oDWpANsflnnx_LfbAaLQ

{
  "title": "String 1",
  "languageId": 1,
  "description": "Bunda string haqida urganamiz",
  "maxRate": 8
}


### Problem qo`shish
POST http://localhost:8090/api/problem
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBjb2RpbmdiYXQuY29tIiwiaWF0IjoxNjYzODE2OTM4LCJleHAiOjE2NjM4ODg5Mzh9.n2xOGnDXT-ju1XRsqp1J_Ir5QY5mHulE1zj2NdC3T8_qS5i3OEIFkMHhYD2KB7Ed5SBarnu1Su6xJI3T8k4dNw

{
  "title": "concat",
  "description": "middle range",
  "methodSignature": "public String concat(String a, String b){}",
  "section": 1,
  "cases": [
    {
      "args": "\"a\", \"b\"",
      "expected": "\"ab\"",
      "visible": true
    },
    {
      "args": "\"ketmon\", \"bolta\"",
      "expected": "\"ketmonbolta\"",
      "visible": true
    }
  ]
}








### Update
PUT http://localhost:8090/api/problem/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBjb2RpbmdiYXQuY29tIiwiaWF0IjoxNjYzNjU2NDAzLCJleHAiOjE2NjM3Mjg0MDN9.FvLDuYL62UEa1elWcwt8RX8E5fGpL4SAMtvuAT_Hu94UyIwk3_UKcfPTacRs7FmOK5oDWpANsflnnx_LfbAaLQ

{
  "title": "concat",
  "description": "middle range",
  "methodSignature": "public String concat(String a, String b){}",
  "section": 1,
  "cases": [
    {
      "args": "\"a\", \"b\"",
      "expected": "\"adsCWdb\"",
      "visible": true
    },
    {
      "id": 2,
      "args": "\"ketmon\", \"bolta\"",
      "expected": "\"ketmonsXZcbolta\"",
      "visible": false
    }
  ]
}